- include/gridtools/common/tuple.hpp
Fix a problem with get<>() for tuple in gcc 5.3.
> Fix tuple get

- include/gridtools/storage/data_store.hpp
- include/gridtools/storage/storage_cuda/cuda_storage.hpp
- include/gridtools/storage/storage_host/host_storage.hpp
- include/gridtools/storage/storage_mc/mc_storage.hpp
Parallel storage initialization if OpenMP is enabled. Parallelization gives huge speedups on manycore processors, e.g. about factor 10 in total run time for performance tests on KNL.
> Use Multiple Threads in Storage Initialization

- pyutils/pyutils/runtools.py
- Be more patient with sacct, wait up to 90 seconds for exit codes (before was 10s).
- Raise proper error when sacct still fails.
- Improved error messages on sbatch job submission.
> Improved PyUtils Behavior on Incomplete `sacct` Output

- jenkins/run_tests.sh
Since MPI tests need 4 nodes we have a long queuing time. Additionally communication parts are changed rarely. Therefore we introduce a new plan to run tests with MPI (`launch mpistrgrid`), while the standard plans `strgrid` and `icgrid` test without MPI communication.
> Jenkins: Make running MPI optional

- include/gridtools/storage/data_store.hpp
The "external constructor" gets a pointer (which must be non-zero). So there is no need to make sure that the length of the data is non-zero.
This fix is needed, because the check uses data (halo sizes) which is not needed for the external interface and may be wrongly initialized.
Required for GT4Py
> Fix "external constructor" for data store

- include/gridtools/common/array.hpp
- include/gridtools/common/defs.hpp
- include/gridtools/common/generic_metafunctions/const_ref.hpp
- include/gridtools/common/gt_assert.hpp
- include/gridtools/common/pair.hpp
- include/gridtools/common/tuple.hpp
- include/gridtools/common/tuple_util.hpp
- include/gridtools/stencil_composition/expressions/expr_base.hpp
- include/gridtools/stencil_composition/sid/composite.hpp
- include/gridtools/stencil_composition/stencil_functions.hpp
- jenkins/envs/kesch.sh
- unit_tests/common/test_pair.cpp
- unit_tests/common/test_tuple.cu
- sets `GT_CONSTEXPR` to `constexpr` for nvcc
- introduces `const_ref` to fix performance for CUDA >= 9.2 (`T` for small data types, `T const&` for large data types)
Backport to GridTools 1.0. See also #1326 and 9bb2d6402569e1d4bd95239999213a647504dc9c
> Fix performance for CUDA >= 9.2 (GT v1.0-branch)

- jenkins/setup.sh
- pyutils/driver.py
- pyutils/perftest/stencils/structured.py
- pyutils/pyutils/runtools.py
This introduces scheduling of a single SLURM job with sequential test execution instead of an array job that overloaded SLURM on Daint (we seem to have a scheduler that’s too overstrained to schedule).
> PyUtils: Workaround for Slow SLURM

- include/gridtools/communication/low_level/proc_grids_3D.hpp
If `m_coordines[x] == 0` and `X == -1`, we might do `-1 % N`. The sign of the result was implementation-defined pre-stdc++11; in GCC 7.3 this is incorrectly still negative, which leads to problems with MPI later in the code.
(Maybe), backport to gridtools 1.0 required.
> Fix modulo in GCL

- jenkins/envs/tave_icc.sh
Revert GCC and Intel compiler versions to default versions before maintenance.
> Fix Tave Environment

- include/gridtools/common/defs.hpp
- include/gridtools/stencil_composition/backend_cuda/entry_point.hpp
- include/gridtools/stencil_composition/backend_cuda/fused_mss_loop_cuda.hpp
- include/gridtools/stencil_composition/execution_types.hpp
Move the k-block-size parameter into the CUDA backend for consistency with i- and j-block-sizes.
> Uniform Block-Sizes API

- include/gridtools/stencil_composition/expressions/expr_base.hpp
Fixes a missing include that might trigger an error in user code if `gridtools/stencil_composition/expressions/expressions.hpp` is the first included GridTools header.
> Fix Missing Include in expr_base.hpp

- include/gridtools/storage/data_view.hpp
`storage_info` is sometimes called within a `GT_FUNCTION` (in the boundary conditions, the user gets a `data_view` which we might want to query).
Thus, also this function has to be `GT_FUNCTION`.
> `storage_info` has to be `GT_FUNCTION`

- cmake/workaround_mpi.cmake
When doing find_package( GridTools ) and it so happens that the CMake policy `CMP0057` is not set to ON (default = OFF), then the `IN_LIST` keyword is not recognized.
This commit sets the policy, just within the function scope.
> Added missing cmake_policy in workaround_mpi.cmake

- cmake/workaround_mpi.cmake
When doing find_package( GridTools ) and it so happens that the CMake policy `CMP0057` is not set to ON (default = OFF), then the `IN_LIST` keyword is not recognized.
This commit sets the policy, just within the function scope.
> Added missing cmake_policy in workaround_mpi.cmake (#1394)

- include/gridtools/stencil_composition/frontend/cartesian/stencil_functions.hpp
GCC (especially versions < 9) had problems vectorizing `call` and `call_proc` usages. This PR improves this. Clang still has vectorization issues (might or might not be related to `call` and `call_proc`).
> Better `call` and `call_proc` Vectorization

- cmake/public/gridtools_setup_targets.cmake
- tests/CMakeLists.txt
- tests/cmake/CMakeLists.txt
- tests/cmake/README.md
- tests/cmake/storage_cuda/CMakeLists.txt
- tests/cmake/storage_cuda/main.cpp
- tests/cmake/test_driver.sh.in
Adds infrastructure for testing CMake projects using GridTools:
- Put a CMake project in `test/cmake/<testname>`.
- Add `add_cmake_test(<testname>)`.
- The CMake project should produce an executable called main which exits with exit code 0 on success. Later, this can be refined as needed.
- The configure & build & run will run as part of ctest with lable `cmake`.
> CMake test: storage_cuda without CUDA compiler

- jenkins/setup.sh
There is a bug on daint where file handles might be broken in /tmp. When trying to access these files, the command will be stuck forever. This happened very often in the last couple of days. The problem is in the `find ...` command. Putting logfiles in a subfolder should workaround  this issue.
> Workaround /tmp blocking issue on daint

- jenkins/setup.sh
This makes Jenkins log files accessible to all users, preventing access right problems.
> Fix Logfile Permissions

- README.md
- cmake/definitions.cmake
- docs_src/manuals/getting_started/code/CMakeLists.txt
Update README to reflect that Intel compiler might not work with GridTools.
Fixes #1494
> Hide Intel compiler options from nvcc

- pyutils/driver.py
- pyutils/test/__init__.py
Enables running of examples after they have been built. Addresses #1470.
> PyUtils: Run Examples

- include/gridtools/common/pair.hpp
Compiler version:
```
clang version 10.0.0 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/sbin
```
> Fix compilation errors in test_pair (use std::size_t instead of size_t)

- include/gridtools/boundary_conditions/boundary.hpp
Currently, the cuda backend for boundary conditions is only specialized for the default cuda backend, but not for the one with custom block sizes. This PR changes that behaviour.
> Boundary conditions must be templated on block size

- include/gridtools/common/atomic_functions.hpp
- include/gridtools/common/generic_metafunctions/for_each.hpp
- include/gridtools/common/tuple.hpp
- include/gridtools/common/tuple_util.hpp
- include/gridtools/stencil/frontend/expandable_run.hpp
- include/gridtools/stencil/frontend/run.hpp
- include/gridtools/storage/builder.hpp
- tests/include/test_environment.hpp
- tests/regression/icosahedral/neighbours_of.hpp
- tests/unit_tests/common/test_atomic_functions.cpp
- tests/unit_tests/stencil/frontend/cartesian/test_expressions.cpp
- tests/unit_tests/stencil/frontend/cartesian/test_kcache_fill.cpp
- tests/unit_tests/stencil/frontend/cartesian/test_kcache_fill_and_flush.cpp
- tests/unit_tests/stencil/frontend/cartesian/test_kcache_flush.cpp
- tests/unit_tests/stencil/frontend/cartesian/test_kcache_local.cpp
- tests/unit_tests/stencil/frontend/cartesian/test_multi_types.cpp
Fixes compilation for `for_each` with an empty list on GCC in combination with `-Wpedantic`. Further, many warnings using `-Wpedantic` are fixed by removing unnecessary semicolons, replacing compound literals and avoiding variable-length arrays.
> Fix Compilation and Warnings for -Wpedantic

- include/gridtools/sid/as_const.hpp
- include/gridtools/sid/block.hpp
- include/gridtools/sid/delegate.hpp
- include/gridtools/sid/rename_dimension.hpp
- include/gridtools/sid/sid_shift_origin.hpp
- tests/unit_tests/sid/test_sid_delegate.cpp
- tests/unit_tests/sid/test_sid_rename_dimension.cpp
`delegate` helper was redesigned. Now it implements only those concept functions that are defined in the source SID. In the previous design all concept functions were defined (including those that are fall back to default for the source SID). As a result it was a lot of hard to debug compilation errors.
> fix the bug with delegating optional concept functions

- include/gridtools/common/tuple_util.hpp
In the original location the static_assert is probably not triggered because the whole function is SFINAE disabled. Not sure if we should add the protection.
> Fix static_assert for transpose empty tuple

- include/gridtools/stencil/be_api.hpp
- include/gridtools/stencil/core/functor_metafunctions.hpp
- include/gridtools/stencil/gpu/entry_point.hpp
- include/gridtools/stencil/gpu/fill_flush.hpp
- tests/unit_tests/stencil/core/test_functor_metafunctions.cpp
- fix the way GT internally splits computation interval into atomic intervals
- add asserts to the k fill/flush implementation against access violation
> K cache related fixes

- docs_src/manuals/getting_started/code/CMakeLists.txt
- include/gridtools/common/integral_constant.hpp
- include/gridtools/common/tuple_util.hpp
- include/gridtools/sid/concept.hpp
- include/gridtools/storage/builder.hpp
- include/gridtools/storage/data_store.hpp
- include/gridtools/storage/data_view.hpp
- include/gridtools/storage/gpu.hpp
- include/gridtools/storage/info.hpp
- include/gridtools/storage/sid.hpp
- include/gridtools/storage/traits.hpp
- tests/unit_tests/storage/test_storage_info.cpp
- tests/unit_tests/storage/test_storage_sid.cpp
The changes is the storage API:
- Data store builder `dimensions` method now accepts both integers and integral constants. Type information is propagated to the data store that is built.
- The properly typed lengths and strides are available to the user via the `native_lengths()` and `native_strides()` methods from data_store/view/info.
- Data store sid adapter uses `native_lengths()`/`native_strides()` now. So the knowledge of the compile time lengths is propagated to the SID API
- call operator of the data store view is now also `compile time aware`. I.e. if the dimension offsets are provided as integral constants and all strides are also known in compile time, no stride computations are performed in run time.  
- There are minor backward incompatibilities to the public API:
- …
> compile time lengths support in data stores

- include/gridtools/sid/concept.hpp
- include/gridtools/sid/loop.hpp
- include/gridtools/sid/multi_shift.hpp
- include/gridtools/sid/sid_shift_origin.hpp
- include/gridtools/stencil/cpu_kfirst.hpp
- include/gridtools/stencil/frontend/cartesian/stage.hpp
- include/gridtools/stencil/frontend/icosahedral/stage.hpp
- tests/unit_tests/sid/test_sid_concept.cpp
- tests/unit_tests/sid/test_sid_loop.cpp
- `sid::shifted` and `sid::multi_shifted` helpers are added
- `sid::shift` can also accept now R-value as a pointer. In this case it is a noop.
-  `sid::loop` API is extended to accept `(Ptr&&, Strides const&)` (was only `(Ptr&, Strides const&)` previously). This means that now one can write: `sid::make_loop<dim::i>(size_i)(body)(origin(), strides);` instead of `auto ptr = origin(); sid::make_loop<dim::i>(size_i)(body)(ptr, strides);`. In the first variant the final shift to the initial point will be skipped (techicaly `noop` overload will be used for the final shift).
> Minor changes to sid

- cmake/public/gridtools_setup_targets.cmake
- include/gridtools/stencil/core/backend.hpp
- include/gridtools/stencil/core/convert_fe_to_be_spec.hpp
- include/gridtools/stencil/core/functor_metafunctions.hpp
- include/gridtools/stencil/dump.hpp
- include/gridtools/stencil/frontend/cartesian/tmp_arg.hpp
- include/gridtools/stencil/frontend/expandable_run.hpp
- include/gridtools/stencil/frontend/icosahedral/tmp_arg.hpp
- include/gridtools/stencil/frontend/run.hpp
- tests/regression/CMakeLists.txt
- tests/regression/dump.cpp
Stencil `dump` backend is added. It doesn't perform calculations. Instead it outputs `JSON` representation of the spec (the type that is passed to the backend entry point). Unlike other backends `dump` is stateful -- it contains the reference to the `std::ostream` that is served as an output sink. The usage is like that:
```
run(fe_spec, dump{std::cout}, ...);
```
The context of this PR is the following: It is a step to extract the cosmo dycore model from the gt2 based source and to pass it into gt4py in the future. The main showstopper on this way is the fact that the elementary stencils are represented in the generated `json` as `C++` demangled type names. The next step could be to parse the sources with the python based tool and to extract the AST's from the stencil bodies.
> Introduce dump backend 

- include/gridtools/meta/fold.hpp
`meta::lfold`/`meta::rfold` now use variadic operator expression if compiled with C++17
For the record: on my mac pro the new code reduces compilation time of the fold on the list with 3000 elements from 4 to 2 seconds.
> C++17 implementation of meta fold

- include/gridtools/common/hugepage_alloc.hpp
It's most likely a compiler bug, but the wrong optimization is in the testing code, not in the allocation. See https://portal.cray.com/viewcase?Id=5000b00001fEzJQAA0.
> Revert warning in hugepage_alloc and simplify code

- cmake/public/gridtools_setup_targets.cmake
- examples/CMakeLists.txt
- examples/c_bindings/CMakeLists.txt.in
- examples/cmake_skeletons/CMakeLists.txt.driver.in
- examples/cmake_skeletons/CMakeLists.txt.example.in
- examples/stencil_type_erasure/CMakeLists.txt.in
- jenkins/envs/daint_cray_cxx17.sh
- jenkins/envs/daint_nvcc_gcc_cxx17.sh
- jenkins/setup.sh
- tests/CMakeLists.txt
Add cray_cxx_17 environment which enables C++17 for tests.
Unrelated:
- Improve testing setup for examples, they nearly work with Cray except for #1575
> CMake + Jenkins: add c++17 testing

- jenkins/envs/dom.sh
- jenkins/envs/dom_nvcc_gcc.sh
Add nvcc_gcc environment for dom, enable dom release plan on jenkins.
For reference: for whatever reason the debug build doesn't work on jenkins (doesn't detect CUDA), but works if I ran the plan myself.
> Jenkins: add dom env

- include/gridtools/common/hugepage_alloc.hpp
- tests/unit_tests/common/test_hugepage_alloc.cpp
This improves the behavior of hugepage_alloc in several ways (fixes #1561):
- Fixed hardcoded values: queries architecture-dependent L1 cache line size and set size at run time (Linux only).
- More conservative offsetting: makes sure that each cache set is considered.
- Explicit control over huge page allocation: introduces the environment variable GT_HUGEPAGE_MODE that can be used to switch between explicit huge page allocation, use of transparent huge pages and disabling huge pages (Linux only).
> Improvemements for Hugepage Allocation

- include/gridtools/sid/concept.hpp
- tests/unit_tests/sid/test_sid_concept.cpp
Replace C++ version check by feature test macro for concepts.
E.g. GCC 9 reports `201709L` for `-std=c++2a` but doesn't have concepts support.
> Fix C++ concepts detection

- include/gridtools/common/host_device.hpp
- include/gridtools/common/hugepage_alloc.hpp
- include/gridtools/common/iterate_on_host_device.hpp
This PR protects against a fragile design pattern that I already observed in `gtc` code:
`foo.hpp`:
```c++
void foo() {device::bar();}
```
`baz.cpp`:
```c++
#include "foo.hpp"
int main() {foo();}  // ok
```
`baz.cu`
```c++
#include "foo.hpp"
int main {foo();} // opps
```
> Add protection against misuse of device namespace

- .github/workflows/tests.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Fix Environment Variables in Github Workflows

- include/gridtools/common/omp.hpp
- jenkins/envs/ault_hip.sh
This enables all AMD GPU nodes on Ault for possible execution of the tests.
> More stable ROCm Environment on Ault

- include/gridtools/common/tuple_util.hpp
My CUDA compiler (11.2) doesn't find the `select_arg` on device.
> CUDA fix for tuple_util::concat: remove constexpr var

- include/gridtools/sid/as_const.hpp
With C++17, `as_const` was added into the standard and if `as_const` is not called qualified, we end up with `std::as_const` (which is also a better match) in most cases because there is some `std` inside one of the template arguments.
By qualifying `as_const`, performance is fixed.
For GTBench, performance is identical with `-std=c++14` and `-std=c++17` now.
> Fix performance with C++17

- include/gridtools/storage/adapter/python_sid_adapter.hpp
Python integer format char is ambiguous and platform dependent. PyBind11 `format_descriptor<...>::format()` always returns "q" and "Q" for 64bit integers, independent of the platform. Compatible passed-in Python buffers on the other hand might also have the equivalent format "l" or "L" set. See https://github.com/pybind/pybind11/issues/1806 and https://github.com/pybind/pybind11/issues/1908 for details. This fix introduces a special case for integer format comparisons, just checking size and signedness.
> Fix for Integer Format Check in Python SID Adapter

- include/gridtools/storage/adapter/python_sid_adapter.hpp
- tests/regression/py_bindings/driver.py
- tests/regression/py_bindings/implementation.cpp
Adds `UnitStrideDim` argument to Python SID adapter to support the same unit-stride assumptions in GT4Py as with GT 1.1.
> Support for Compile-Time Unit Stride Dimension for Python SID Adapter

- include/gridtools/common/for_each.hpp
- include/gridtools/meta/macros.hpp
- include/gridtools/reduction/gpu.hpp
This are the changes needed for CUDA 11.4
- There is a problem with `for_each` being a constexpr value. This is reported and we will see whether this is considered part of CUDA constexpr interpretation.
- `sizeof...` is still not fixed ==> Will try to get an update on the state of the issue.
- reduction: There seems a problem in GCC 7.5, which is still used in some of our systems as a default. As this is a trivial workaround, I propose to do this.
> Fix cuda 11 4

- .github/workflows/tests.yml
I recently updated the `gridtools-docker` repository and changed the tag of the former hip container, due to a second hip instance needed for the GHEX CI. I can easily revert back to the previous one in case of any issue.
> Update hip container label, according to latest updates in gridtools-docker

- README.md
- docs_src/manuals/getting_started/CMakeLists.txt
Propagate `CMAKE_CXX_FLAGS` to examples sub-project.
> Intel with -qnextgen support

- include/gridtools/common/hymap.hpp
- include/gridtools/meta.hpp
- include/gridtools/meta/val.hpp
- include/gridtools/sid/concept.hpp
- tests/unit_tests/common/test_hymap.cpp
- add `element_at` to `hymap` library
- introduce `meta::val` and friends
- fix a bug in `hymap::from_meta_map`
- soften sid value type requirements from `std::trivaly_copyablle`  to `std::trivially_copy_constructible`
> Extensions to meta and hymap

- include/gridtools/sid/allocator.hpp
- include/gridtools/sid/simple_ptr_holder.hpp
- tests/unit_tests/sid/test_sid_as_const.cpp
- tests/unit_tests/sid/test_sid_composite.cpp
- tests/unit_tests/sid/test_sid_delegate.cpp
- tests/unit_tests/sid/test_sid_rename_dimensions.cpp
- tests/unit_tests/sid/test_sid_shift_sid_origin.cpp
- tests/unit_tests/sid/test_sid_synthetic.cpp
Not sure if it's worth trading aggregate for CTAD. When I looked at make_simple_ptr_holder, I missed that aggregate CTAD is a C++20 feature.
> CTAD for simple_ptr_holder

- include/gridtools/common/cuda_util.hpp
- include/gridtools/fn/backend/gpu.hpp
- include/gridtools/fn/cartesian.hpp
- include/gridtools/fn/executor.hpp
- include/gridtools/fn/run.hpp
- include/gridtools/fn/unstructured.hpp
- include/gridtools/stencil/gpu/launch_kernel.hpp
- include/gridtools/stencil/gpu_horizontal/launch_kernel.hpp
- tests/regression/fn/fn_tridiagonal_solve.cpp
The `fn::gpu` backend now supports setting the CUDA stream in which the kernel is launched.
> fn: allow setting CUDA stream

- include/gridtools/gcl/high_level/descriptor_generic_manual.hpp
- include/gridtools/gcl/high_level/empty_field_base.hpp
Similar to #1710, but in GCL. Bug was triggered in GTBench.
> Workaround for Bug in Recent NVCC Versions (at least 11.6, 11.7)

- tests/regression/CMakeLists.txt
Fixes #1551. You cannot make a CMake target with no sources and no linker input, so this adds a dummy source file to the perftests target for when there are no linker inputs either.
> Fix perftests CMake target being empty: https://github.com/GridTools/gridtools/issues/1551

- AUTHORS
- include/gridtools/fn/sid_neighbor_table.hpp
- tests/unit_tests/fn/CMakeLists.txt
- tests/unit_tests/fn/test_fn_sid_neighbor_table.cpp
- tests/unit_tests/fn/test_fn_sid_neighbor_table.cu
Adds a simple class that wraps an SID and implements the neighbour table concept. This makes it possible to use Python buffers as neighbour tables by first wrapping them into an SID, but any SID is suitable as a neighbour table.
> Using SIDs as neighbour tables in functional API

- include/gridtools/fn/column_stage.hpp
- include/gridtools/fn/sid_neighbor_table.hpp
- include/gridtools/fn/unstructured.hpp
nvcc 12.0 crashes in the test_fn_sid_neighbor_table
Additionally: suppress some invalid nvcc warnings
> Fix CUDA 12.0 compilation

- AUTHORS
- include/gridtools/storage/adapter/python_sid_adapter.hpp
- tests/regression/py_bindings/CMakeLists.txt
- tests/regression/py_bindings/driver.py
Light-weight PR to make the Python bindings work with AMD GPU buffers. Complementary to https://github.com/GridTools/gt4py/pull/1278.
> Python: Add support for HIP/ROCm buffers

- .github/workflows/tests.yml
- include/gridtools/common/defs.hpp
- include/gridtools/fn/column_stage.hpp
- include/gridtools/storage/builder.hpp
- include/gridtools/storage/data_store.hpp
- tests/include/nvcc_workarounds.hpp
- tests/regression/fn/fn_cartesian_vertical_advection.cpp
- tests/regression/fn/fn_domain.cpp
- tests/regression/fn/fn_tridiagonal_solve.cpp
- tests/unit_tests/common/test_tuple.cpp
- tests/unit_tests/fn/test_fn_column_stage.cpp
CUDA 12.1 and 12.2 have a problem with constexpr, e.g. in the context of CTAD, see #1766. The workaround is to do pre-C++17 `make_tuple`-construction or construct from a (possibly moved-from) lvalue.
CI: add GCC + CUDA 12.1/12.2 and NVHPC 23.7
> Workarounds for CUDA 12.1 and 12.2

- include/gridtools/storage/gpu.hpp
not sure why this should be inside an `#if defined(GT_CUDA_ARCH)`
> Bug: storage/gpu.h functions within __CUDA_ARCH__

- include/gridtools/storage/adapter/nanobind_adapter.hpp
- tests/unit_tests/storage/adapter/CMakeLists.txt
- tests/unit_tests/storage/adapter/test_nanobind_adapter.cpp
- nb::any is replaced by `ssize_t(-1)`
- Because of a change in `~ndarray`, we need to make sure that Python is initialized in our tests (see https://github.com/wjakob/nanobind/issues/377)
> Update nanobind to v2

- .github/workflows/tests.yml
- include/gridtools/common/defs.hpp
Partially fixes CUDA 12.4 problems. There are more problems which where not in 12.3, but these tests are not covered by GitHub action tests (which are only the perftests).
> CI: test CUDA 12.4

- tests/unit_tests/common/test_hugepage_alloc.cpp
test_hugepage_alloc.cpp is using uintptr_t (optional, btw). It seems like there is no implicit include of cstdint because we have a failure in very recent compilers.
3700 .../files/gridtools/sources/tests/unit_tests/common/test_hugepage_alloc.cpp(68): error: namespace "std" has no member "uintptr_t"
3701              reinterpret_cast<std::uintptr_t>(ptr) % hugepage_alloc_impl_::cache_line_size()
> Fix include for test_hugepage_alloc.cpp
