- jenkins/plot_full_comparison.sh
- pyutils/perftest/__init__.py
- pyutils/perftest/plot.py
- Fix plotting from source directory (without available buildinfo).
- Fix display of compiler + version in plots
- Improve comparison plotting with many results
- Jenkins script for per-machine comparison plots
> PyUtils Fixes

- pyutils/perftest/__init__.py
Accidentally killed perftests by last change.
> Fix Perftests

- jenkins/plot_full_comparison.sh
Correctly loads Python environment for executing machine.
> Fix Full Performance Comparison Plotting on Jenkins

- docs_src/manuals/user_manual/storages.hrst
`select_*` are not used correctly. These codes would not compile like this.
No jenkins required.
> fix documentation for storages

- pyutils/perftest/plot.py
- Fix missing data in plots with more than 7 results.
- Sort plotted data in history plots.
> PyUtils: Fix History Plots

- pyutils/pyutils/runtools.py
Fixes error in rare cases where exactly half of the jobs failed.
> Fix for PyUtils

- include/gridtools/communication/low_level/proc_grids_3D.hpp
> Fix modulo in GCL - backport

- cmake/definitions.cmake
- docs_src/manuals/getting_started/CMakeLists.txt
- examples/CMakeLists.txt
Fix several `CMAKE_BINARY_DIR` -> `PROJECT_BINARY_DIR`
> Support for superbuilds (#1383)

- include/gridtools/stencil_composition/frontend/axis.hpp
- tests/unit_tests/stencil_composition/frontend/cartesian/test_kcache_fill.cpp
- tests/unit_tests/stencil_composition/frontend/cartesian/test_kcache_fill_and_flush.cpp
- tests/unit_tests/stencil_composition/frontend/cartesian/test_kcache_flush.cpp
- tests/unit_tests/stencil_composition/frontend/cartesian/test_kcache_local.cpp
- tests/unit_tests/stencil_composition/frontend/cartesian/test_kparallel.cpp
- tests/unit_tests/stencil_composition/frontend/test_grid.cpp
> Remove ExtraOffsetsAroundFullInterval

- .github/workflows/tests.yml
- pyutils/driver.py
- pyutils/test/__init__.py
Only build and run a subset of tests on GitHub CI again.
Fixes #1465
> Reintroduce --perftests-only

- include/gridtools/gcl/GCL.hpp
> Defaults for gcl::init()

- include/gridtools/common/tuple_util.hpp
- include/gridtools/meta/macros.hpp
- include/gridtools/sid/composite.hpp
Required fixes to compile CUDA 11.
> Fixes for CUDA 11

- include/gridtools/common/tuple_util.hpp
- include/gridtools/meta/macros.hpp
- include/gridtools/stencil_composition/sid/composite.hpp
Required fixes to compile CUDA 11.
> GT v1.1: Fixes for CUDA 11

- include/gridtools/stencil_composition/sid/sid_shift_origin.hpp
For master, this was already fixed I think.
> GT v1.1: Fix sid shift origin

- docs_src/manuals/user_manual/execution_model.hrst
Minor grammar fixes found when reading through.
> Execution model grammar fixes

- include/gridtools/storage/adapter/python_sid_adapter.hpp
- tests/regression/CMakeLists.txt
- tests/regression/py_bindings/CMakeLists.txt
- tests/regression/py_bindings/driver.py
- tests/regression/py_bindings/implementation.cpp
- `SID` adapter for `pybind11` buffers is introduced
- python binding is added to the regression set
> Py bindings

- include/gridtools/sid/concept.hpp
- include/gridtools/sid/loop.hpp
- include/gridtools/stencil/frontend/run.hpp
- include/gridtools/stencil/gpu/fill_flush.hpp
- `get_lower_bound`/`get_upper_bound` helpers are added to the sid concept
- SID boundaries API is documented
> Document SID bounds API

- include/gridtools/sid/concept.hpp
- tests/unit_tests/sid/test_sid_concept.cpp
This PR demonstrates how the actual sid infrastructure fit C++20 concepts.
> Sid as a proper C++20 concept

- jenkins/envs/ault.sh
- jenkins/envs/ault_hip.sh
Required due to recent maintenance.
> Fix for Ault CI Environment

- include/gridtools/stencil_composition/stage_matrix.hpp
This change speeds up compilation by 2-3%
> GT v1.1: Increase compilation speed (backport from GT v2)

- README.md
- include/gridtools/stencil/cpu_ifirst/loops.hpp
- jenkins/envs/ault.sh
- jenkins/envs/ault_hip.sh
- jenkins/envs/daint.sh
- jenkins/envs/daint_cray.sh
- jenkins/envs/daint_cray_cxx17.sh
- jenkins/envs/daint_nvcc_clang.sh
- jenkins/envs/dom.sh
- jenkins/envs/dom_nvcc_gcc.sh
- jenkins/setup.sh
- tests/regression/CMakeLists.txt
- tests/unit_tests/common/test_hugepage_alloc.cpp
- tests/unit_tests/common/test_tuple.cu
Passes all setups except ault-hip.
> CI: Update modules for GT v2.0

- include/gridtools/fn/domain_extender.hpp
- include/gridtools/meta/macros.hpp
- tests/regression/fn/fn_hd.cpp
- tests/regression/fn/fn_lap.cpp
- tests/regression/fn/fn_nabla.cpp
- tests/regression/parallel_multistage_fusion.cpp
- tests/unit_tests/fn/test_fn_offsets.cpp
- tests/unit_tests/sid/test_sid_composite.cpp
- tests/unit_tests/sid/test_sid_rename_dimensions.cpp
- fix nvcc11.5 compilation
- fix clang12 compilation with c++20
> Compilation fixes

- include/gridtools/common/tuple.hpp
- include/gridtools/common/tuple_util.hpp
- tests/unit_tests/common/test_tuple.cpp
- tests/unit_tests/common/test_tuple_util.cpp
> Implement is_tuple_like

- include/gridtools/common/hymap.hpp
- include/gridtools/common/tuple.hpp
- include/gridtools/common/tuple_util.hpp
- tests/unit_tests/common/test_hymap.cpp
- tests/unit_tests/common/test_tuple.cpp
- tests/unit_tests/common/test_tuple_util.cpp
> Implement is_hymap

- jenkins/run_perftest_PR.sh
- jenkins/update_references.sh
- Fix for failure because of missing references.
- Updated config names in update_references.sh.
> Perftest Updates

- include/gridtools/common/hymap.hpp
- include/gridtools/fn/backend/naive/apply.hpp
- include/gridtools/fn/backend2/common.hpp
- include/gridtools/fn/backend2/gpu.hpp
- include/gridtools/fn/backend2/naive.hpp
- tests/unit_tests/common/test_hymap.cpp
- tests/unit_tests/fn/CMakeLists.txt
- tests/unit_tests/fn/test_fn_backend_gpu.cu
- tests/unit_tests/fn/test_fn_backend_naive.cpp
New naive and GPU fn backend backends. Providing the functions `apply_stencil_stage`, `apply_columns_stage`, `tmp_allocator` and `allocate_global_tmp`.
> Fn: New Backend Backends

- tests/unit_tests/fn/test_fn_backend_gpu.cu
- tests/unit_tests/fn/test_fn_backend_naive.cpp
- tests/unit_tests/fn/test_fn_cartesian_gpu.cu
- tests/unit_tests/fn/test_fn_column_stage.cpp
- tests/unit_tests/fn/test_fn_column_stage.cu
- tests/unit_tests/fn/test_fn_stencil_stage.cpp
- tests/unit_tests/fn/test_fn_unstructured_gpu.cu
> Remove usage of make_simple_ptr_holder -> CTAD

- include/gridtools/fn/common_interface.hpp
- tests/regression/fn/fn_cartesian_vertical_advection.cpp
- tests/regression/fn/fn_unstructured_nabla.cpp
Add tuple builtins to be closer to the IR spec and simplify code generation.
> Add fn::tuple_get and fn::make_tuple

- include/gridtools/storage/adapter/python_sid_adapter.hpp
The sid from `as_sid(pybind11::buffer)` has view semantics, copying means copying the view.
> Make pybind11::buffer sid copyable
